# Move day-to-day shell tools scripts to path

install:
  @echo 'Installing scripts'

  @echo '-> Installing dataHandler.sh'
  @cp dataHandler.sh /usr/local/bin/

  @echo '-> Installing extractGHrepos.sh'
  @cp extractGHrepos.sh /usr/local/bin/
  
  @echo '-> Installing pdfComp.sh'
  @cp pdfComp.sh /usr/local/bin/
  
uninstall:
  @echo 'Uninstalling all scripts'
  @rm -f /usr/local/bin/dataHandler.sh
  @rm -f /usr/local/bin/extractGHrepos.sh
  @rm -f /usr/local/bin/pdfComp.sh